workflows:
  test_and_build:
    name: Test and Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      android:
        ndk: latest
        sdk: latest
      vars:
        PROJECT_NAME: "ditonton"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test --coverage
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - coverage/**

    publishing:
      email:
        recipients:
          - saptrian24@gmail.com
