name: ditonton
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_rating_bar: ^4.0.0
  get_it: ^7.1.3
  google_fonts: ^5.1.0
  http: ^1.1.0
  path_provider: ^2.0.2
  provider: ^6.0.3
  sqflite: ^2.0.0+3
  sqflite_common: ^2.5.4+2

dev_dependencies:
  build_runner: ^2.0.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/
